# Generated by Django 4.1.5 on 2023-04-14 21:30

from django.db import migrations

def make_mihir_staff(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.filter(username='mihir').update(is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230414_2054'),
    ]

    operations = [
        migrations.RunPython(make_mihir_staff),
    ]
