# Generated by Django 4.1.5 on 2023-04-15 19:19

from django.db import migrations
from django.contrib.auth import get_user_model


def add_users(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Staff = apps.get_model('staff', 'Staff')
    Clinic = apps.get_model('staff', 'Clinic')
    User = get_user_model()

    user = Profile.objects.create(username='monika', password="monika", first_name="Monika", last_name="M", email="monika@gmail.com", phone="9013075758",
        blood_group="O+", state="Delhi", city="New Delhi", pincode=110089, date_of_birth="2003-06-15", weight=55, is_staff=True)

    clinic = Clinic.objects.get(clinic_id=10)
    staff = Staff.objects.create(user_id=user, clinic_id=clinic)

    user = User.objects.get(username='monika')
    user.set_password('monika')
    user.save()

    user = Profile.objects.create( username='kevqn', first_name="Guneet", last_name="Aggarwal", email="guneet@gmail.com",
        phone="9754366341", blood_group="O+", state="Delhi", city="New Delhi", pincode=110010, date_of_birth="2003-06-15", weight=49,)
    user = User.objects.get(username='kevqn')
    user.set_password('kevqn')
    user.save()

    user = Profile.objects.create( username='ram_a', first_name="Ram", last_name="Aggarwal", email="ram@yahoo.com",
        phone="9754366311", blood_group="A-", state="Delhi", city="New Delhi", pincode=110029, date_of_birth="2000-12-09", weight=79,)
    user = User.objects.get(username='ram_a')
    user.set_password('ram_a')
    user.save()

    user = Profile.objects.create( username='shyam', first_name="Shyam", last_name="Meena", email="shyam@gmail.com",
        phone="9752966341", blood_group="B+", state="Delhi", city="New Delhi", pincode=110090, date_of_birth="2003-01-06", weight=56,)
    user = User.objects.get(username='shyam')
    user.set_password('shyam')
    user.save()

    user = Profile.objects.create( username='rahul', first_name="Rahul", last_name="Dhawan", email="rahul@reddifmail.com",
        phone="9323496341", blood_group="AB+", state="Maharashtra", city="Mumbai", pincode=4000007, date_of_birth="2003-03-29", weight=49,)
    user = User.objects.get(username='rahul')
    user.set_password('rahul')
    user.save()

    user = Profile.objects.create( username='jappi', first_name="Japneet", last_name="Singh", email="japneet@gmail.com",
        phone="9754366341", blood_group="O+", state="Rajasthan", city="Alwar", pincode=301001, date_of_birth="2003-06-15", weight=75,)
    user = User.objects.get(username='jappi')
    user.set_password('jappi')
    user.save()



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230415_1001'),
        ('staff', '0005_auto_20230416_1201')
    ]

    operations = [
        migrations.RunPython(add_users),
    ]
