# Generated by Django 4.1.7 on 2023-04-16 12:01

from django.db import migrations
def add_appointments(apps, schema_editor):
    Appointment = apps.get_model('staff', 'Appointment')
    User = apps.get_model('users', 'Profile')
    Clinic = apps.get_model('staff', 'Clinic')

    # Appointment.objects.create(user_id=User.objects.get(id=7), clinic_id=Clinic.objects.get(clinic_id=10), type='Donor', datetime_of_appointment='2023-04-13 21:12:00')
    # Appointment.objects.create(user_id=User.objects.get(id=8), clinic_id=Clinic.objects.get(clinic_id=10), type='Donor', datetime_of_appointment='2023-04-14 22:12:00')
    # Appointment.objects.create(user_id=User.objects.get(id=9), clinic_id=Clinic.objects.get(clinic_id=10), type='Donor', datetime_of_appointment='2023-04-15 23:12:00')
    # Appointment.objects.create(user_id=User.objects.get(id=10), clinic_id=Clinic.objects.get(clinic_id=11), type='Donor', datetime_of_appointment='2023-04-16 00:12:00')


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20230415_1933'),
    ]

    operations = [
        migrations.RunPython(add_appointments),
    ]
