# Generated by Django 4.1.5 on 2023-04-16 21:02

from django.db import migrations

def add_money(apps, schema_editor):
    MoneyReceived = apps.get_model('staff', 'MoneyReceived')
    Profile = apps.get_model('users', 'Profile')

    user = Profile.objects.get(username='jappi')
    MoneyReceived.objects.create(user_id=user, amount=500, date_of_payment='2023-04-16')

    user = Profile.objects.get(username='mainak')
    MoneyReceived.objects.create(user_id=user, amount=300, date_of_payment='2023-02-16')

    user = Profile.objects.get(username='jichris')
    MoneyReceived.objects.create(user_id=user, amount=200, date_of_payment='2023-03-16')

    user = Profile.objects.get(username='kevqn')
    MoneyReceived.objects.create(user_id=user, amount=69, date_of_payment='2042-6-9')



class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_moneyreceived'),
        ('users', '0006_auto_20230415_1919')
    ]

    operations = [
        migrations.RunPython(add_money),
    ]
