# Generated by Django 4.1.5 on 2023-04-14 20:54

from django.db import migrations
from users.models import Profile

def add_admin(apps, schema_editor):
    Profile.objects.create(
        username='admin',
        password='admin',
        email="admin@example.com",
        first_name="Mr.",
        last_name="Admin",
        phone="1234567890",
        blood_group="O+",
        state="Delhi",
        city="Delhi",
        pincode=110029,
        date_of_birth="1969-07-16",
        weight=69,
        is_superuser=True,
        )



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230414_1923'),
    ]

    operations = [
        migrations.RunPython(add_admin)
    ]
