# Generated by Django 4.1.7 on 2023-04-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230414_2130'),
    ]

    operations = [
    ]
