# Generated by Django 4.1.7 on 2023-04-15 10:01

from django.db import migrations
from django.contrib.auth import get_user_model
def change_passwords(apps, schema_editor):
    User = get_user_model()
    for user in User.objects.all():
        if user.username == 'admin' :
            continue
        user.set_password(user.password)
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230414_2130'),
    ]

    operations = [
        migrations.RunPython(change_passwords),
    ]
