# Generated by Django 4.1.5 on 2023-04-14 19:17

from django.db import migrations

SQL_QUERIES = """
INSERT INTO staff_clinic VALUES(2,'Door Number-18-516/2/1, Plot Number 1, Health City, Chinnagadili,',530040,'Andhra Pradesh','Apollo Health City');
INSERT INTO staff_clinic VALUES(3,'18-1-3 KGH Down Road, Andhra Pradesh, Near Rajiv Gandhi Statue',530002,'Andhra Pradesh','Mycure Hospital');
INSERT INTO staff_clinic VALUES(4,'NH- 219, Kuppam',517425,'Andhra Pradesh','P.E.S. Institute of Medical Sciences and Research');
INSERT INTO staff_clinic VALUES(5,'GMC Hostel Rd, Christian Basti, Guwahati',781005,'Assam','St. John''s Hospital');
INSERT INTO staff_clinic VALUES(6,'GS Rd, Mathura Nagar, Bormotoria, Guwahati',781022,'Assam','Sun Valley Hospital');
INSERT INTO staff_clinic VALUES(7,'Patna - Aurangabad Rd, Phulwari Sharif, Patna',801507,'Bihar','AIIMS Patna');
INSERT INTO staff_clinic VALUES(8,'Patel Nagar Rd, Patel Nagar, Bihar Sharif',803101,'Bihar','Jeevan Jyoti Superspeciality Hospital');
INSERT INTO staff_clinic VALUES(9,'0, Patliputra Colony, Patna',800013,'Bihar','Sahyog Hospital');
INSERT INTO staff_clinic VALUES(10,'Ansari Nagar East, Gautam Nagar, Ansari Nagar East, New Delhi, Delhi',110029,'Delhi','AIIMS Delhi');
INSERT INTO staff_clinic VALUES(11,'Ansari Nagar East, near to AIIMS Metro Station, New Delhi',110029,'Delhi','Safdarjung Hospital');
INSERT INTO staff_clinic VALUES(12,'2, Chandragupta Marg, Opp Russian Embassy, Chanakyapuri, New Delhi',110021,'Delhi','Primus Super Speciality Hospital');
INSERT INTO staff_clinic VALUES(13,'66A, 2, New Rohtak Rd, near Liberty Cinema, Block 67, Karol Bagh',110005,'Delhi','Apollo Spectra Hospital');
INSERT INTO staff_clinic VALUES(14,'Dona Paula, Dr E Borges Rd, Panaji',403004,'Goa','Manipal Hospitals Goa');
INSERT INTO staff_clinic VALUES(15,'7XQH+W56, Margao Bypass, Cupangale Society, Margao',403601,'Goa','Sunshine Hospital');
INSERT INTO staff_clinic VALUES(16,'Punit Maharaj Rd, near Jaldhara Water World, Balvatika, Tulsibag, Kankaria, Maninagar',380008,'Gujarat','Siddhi Vinayak Hospital');
INSERT INTO staff_clinic VALUES(17,'9PGW+JCF, Via Para Pipaliya, khandheri St, Rajkot',360006,'Gujarat','AIIMS Rajkot');
INSERT INTO staff_clinic VALUES(18,'3HMR+PRF, GJ SH 41, Near Sabarmati Police Station High-Way, Ramnagar, Abu Street Society, Sabarmati, Ahmedabad',380005,'Gujarat','Panchshil Hospital');
INSERT INTO staff_clinic VALUES(19,'Q Block South City 2, Badshahpur Sohna Rd Hwy, Main, Sector 47, Gurugram',122001,'Haryana','Park Hospital');
INSERT INTO staff_clinic VALUES(20,'Plot No. 78-80, Maharishi Parashar Marg, Sector 14, Faridabad',121007,'Haryana','Noble Hospital');
INSERT INTO staff_clinic VALUES(21,'Vivekanand, Chowk, Delhi Rd, behind Bullet Showroom, Janta Colony, Sonipat',131001,'Haryana','Haryana Multispeciality Hospital');
INSERT INTO staff_clinic VALUES(22,'Palampur - Dharamshala Road Adarsh nagar',176001,'Himachal Pradesh','Fortis Hospital, Kangra');
INSERT INTO staff_clinic VALUES(23,'453C+FGM, Cart Rd, Near Local Bus Stand, Lower Bazar, Shimla',171001,'Himachal Pradesh','Deendyal Upadhyay Zonal Hospital');
INSERT INTO staff_clinic VALUES(24,'NH 1, By Pass Road, opp. Channi Himmat, Jammu',180015,'Jammu and Kashmir','Pulse Hospital and Research Center');
INSERT INTO staff_clinic VALUES(25,'City Hospital, Bathindi, Jammu',180007,'Jammu and Kashmir','City Hospital');
INSERT INTO staff_clinic VALUES(26,'CGW5+6J8, Devipur, Simra',814152,'Jharkhand','AIIMS Devipur');
INSERT INTO staff_clinic VALUES(27,'Kanta Toli Chowk, Purulia Rd, Ranchi',834001,'Jharkhand','Jharkhand National Hospital');
INSERT INTO staff_clinic VALUES(28,'No. 85-86, Bangalore-Mysore Ring Road Junction Bannimantapa ''A'' Layout, Siddique Nagar, Mandi Mohalla, Mysuru',570015,'Karnataka','Manipal Hospital Mysore');
INSERT INTO staff_clinic VALUES(29,'Near Rama Takis, Dam Rd, beside 32 foot anjineya statue, Hosapete',583201,'Karnataka','Ashraya Hospita');
INSERT INTO staff_clinic VALUES(30,'2, HKP Road, Sulthangunta, Shivaji Nagar, Bengaluru',560051,'Karnataka','CSI Hospital');
INSERT INTO staff_clinic VALUES(31,'SH17, Rayaradoddi',562159,'Karnataka','GS Hospital');
INSERT INTO staff_clinic VALUES(32,'NH bypass 66, Airport Rd, near Courtyard Garden, Chackai, Thiruvananthapuram',695024,'Kerala','Ananthapuri Hospitals and Research Institute (AHRI)');
INSERT INTO staff_clinic VALUES(33,'Mini Bypass Rd, Govindapuram, Kozhikode',673016,'Kerala','Aster MIMS Hospital');
INSERT INTO staff_clinic VALUES(34,'59XM+4JV, Angamaly, Ernakulam District, Kochi',683572,'Kerala','KG Hospital');
INSERT INTO staff_clinic VALUES(35,'41, Zone-II, Maharana Pratap Nagar, Bhopal',462011,'Madhya Pradesh','Navodaya Hospital & Research Centre');
INSERT INTO staff_clinic VALUES(36,'Anjuman Shopping Complex, No. 321, Parsi, near, Museum Bhanwartal Extension, Napier Town',482001,'Madhya Pradesh','Marble City Hospital');
INSERT INTO staff_clinic VALUES(37,'X52M+CX7, Main road, Sadar, M. P., Narsingpur',487001,'Madhya Pradesh','Reva Shree Hospital');
INSERT INTO staff_clinic VALUES(38,'22PH+PQH, MIHAN, Nagpur, Dahegaon',441108,'Maharashtra','AIIMS Dahegaon');
INSERT INTO staff_clinic VALUES(39,'Mangalwar Peth Rd, near Kasba Post Office, Gandhinagar, Mangalwar Peth, Kasba Peth, Pune',411002,'Maharashtra','Kamla Nehru Hospital');
INSERT INTO staff_clinic VALUES(40,'Pimpri Colony, Mumbai Pune Highway, Pimpri, opposite Pimpri Station, Pimpri-Chinchwad',411017,'Maharashtra','Burute Hospital');
INSERT INTO staff_clinic VALUES(41,'Plot No. 1, Swaminarayan Nagar, New Adgaon Naka, Panchavati, near Lunge Mangal Karyalay, Nashik',422003,'Maharashtra','Apollo Hospitals');
INSERT INTO staff_clinic VALUES(42,'HWRQ+FWR, MDR32, Nongmynsong, Shillong',793019,'Meghalaya','Neigrihms Hospital');
INSERT INTO staff_clinic VALUES(43,'HJ3M+J6W, Mairang',793120,'Meghalaya','Civil Hospital Mairang');
INSERT INTO staff_clinic VALUES(44,'PPJ8+WJJ, Bazar Bungkawn, Bara Bazar, Dawrpui, Aizawl',796001,'Mizoram','Civil Hospital, Aizawl');
INSERT INTO staff_clinic VALUES(45,'Bawngkawn, Aizawl',796014,'Mizoram','Greenwood Hospital');
INSERT INTO staff_clinic VALUES(46,'Kanika Rd, Srivihar Colony, Tulsipur, Cuttack',753008,'Odisha','Sun Hospital Pvt Ltd');
INSERT INTO staff_clinic VALUES(47,'A 54/1, Near Fire Station, Fire Station Square, Baramunda, Bhubaneswar',751003,'Odisha','Vivekanand Hospital Bhubaneswar');
INSERT INTO staff_clinic VALUES(48,'Sijua, Patrapada, Bhubaneswar',751019,'Odisha','AIIMS Bhubaneswar');
INSERT INTO staff_clinic VALUES(49,'AIIMS, Dabwali Road, Bathinda',151001,'Punjab','AIIMS Bathinda');
INSERT INTO staff_clinic VALUES(50,'9, Bibi Wala Rd, Batinda, Bathinda,',151001,'Punjab','Chahal Hospital');
INSERT INTO staff_clinic VALUES(51,'2509/3, Bhushanpura, inside Sultan Wind Gate, Balmiki Mahal, Amritsar Cantt.',143001,'Punjab','Apolo Hospital');
INSERT INTO staff_clinic VALUES(52,'marudar hi industrial area second phase, Basni, Jodhpur',342005,'Rajasthan','AIIMS Jodhpur');
INSERT INTO staff_clinic VALUES(53,'93 B, Ajmer Rd, near DCM, Heera Nagar, Tagore Nagar, Jaipur',302024,'Rajasthan','Asopa Hospital');
INSERT INTO staff_clinic VALUES(54,'A-35, Ajmer Rd, Purani Chungi, Vidhyut Nagar, Jaipur',302021,'Rajasthan','Shubh Hospital');
INSERT INTO staff_clinic VALUES(55,'V2M4+PFH, Madurai',625006,'Tamil Nadu','AIIMS Madurai');
INSERT INTO staff_clinic VALUES(56,'5, 105, Defence Colony 1st Ave, Seven Wells, St.Thomas Mount',600016,'Tamil Nadu','St Thomas Hospital');
INSERT INTO staff_clinic VALUES(57,'95, Pattabiraman Salai, Anna Nagar, Tennur, Tiruchirappalli',620017,'Tamil Nadu','Maruti Hospital');
INSERT INTO staff_clinic VALUES(58,'Main, Haridwar Rd, Jogiwala, Chowk, Dehradun',248001,'Uttarakhand','Kailash Hospital Dehradun');
INSERT INTO staff_clinic VALUES(59,'Mussoorie, Diversion Road, Dehradun',248001,'Uttarakhand','Max Super Speciality Hospital Dehradun');
INSERT INTO staff_clinic VALUES(60,'Atta Market, Pocket E, Sector 27, Noida',201301,'Uttar Pradesh','Vinayak Hospital');
INSERT INTO staff_clinic VALUES(61,'FGQC+V5P, The Hope Hospital, Nursing Home 20, opp. Mother Dairy, Delta II, Greater Noida',201308,'Uttar Pradesh','The Hope Hospital');
INSERT INTO staff_clinic VALUES(62,'12, Uttar Pradesh',201009,'Uttar Pradesh','KIIMS Hospital');
INSERT INTO staff_clinic VALUES(63,'R-11, Sector 12, VAKEEL COLONY, Pratap Vihar, Ghaziabad',201001,'Uttar Pradesh','Astha Hospital');
INSERT INTO staff_clinic VALUES(64,'NH2, Grand Trunk Rd, Gangpur',713104,'West Bengal','CAMRI Hospital');
INSERT INTO staff_clinic VALUES(65,'NH - 34 Connector Basantapur, Saguna, Kalyani',741245,'West Bengal','AIIMS Kalyani');
INSERT INTO staff_clinic VALUES(66,'IB-193, Broadway Rd, IB Block, Sector III, Bidhannagar, Kolkata',700106,'West Bengal','Manipal Hospital, Salt Lake');
INSERT INTO staff_clinic VALUES(67,'GT Road, opposite Axis Bank Branch, Bandel',712123,'West Bengal','ESI Hospital');
"""

class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001a'),
    ]

    operations = [
        migrations.RunSQL(SQL_QUERIES),
    ]
