# Generated by Django 4.1.5 on 2023-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
