# Generated by Django 4.1.5 on 2023-04-12 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_clinic_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorappointment',
            name='datetime_of_booking',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='datetime_of_booking',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
