# Generated by Django 4.1.5 on 2023-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_donorappointment_datetime_of_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(default='Abcd', max_length=200),
            preserve_default=False,
        ),
    ]
