# Generated by Django 4.1.5 on 2023-04-12 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0004_clinic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='clinic_id',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='user_id',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DONOR', 'Donor'), ('PATIENT', 'Patient')], max_length=10)),
                ('datetime_of_appointment', models.DateTimeField()),
                ('datetime_of_booking', models.DateTimeField(auto_now_add=True)),
                ('appointment_fullfilled', models.BooleanField(default=False)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.clinic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bloodfromdonor',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.appointment'),
        ),
        migrations.AlterField(
            model_name='bloodtopatient',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.appointment'),
        ),
        migrations.DeleteModel(
            name='DonorAppointment',
        ),
        migrations.DeleteModel(
            name='PatientAppointment',
        ),
    ]
