# Generated by Django 4.1.7 on 2023-04-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20230414_2141'),
    ]

    operations = [
    ]
