# Generated by Django 4.1.5 on 2023-04-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_patientappointment_clinic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('Donor', 'Donor'), ('Patient', 'Patient')], max_length=10),
        ),
    ]
