# Generated by Django 4.1.5 on 2023-04-17 12:39



from django.db import migrations

SQL_QUERIES = """
create or replace trigger bloodavailable_add after insert on staff_bloodfromdonor
for each row
    update staff_bloodavailable set units_available=units_available+1
    where
        blood_group=(
            select users_profile.blood_group from staff_appointment, users_profile
            where
                staff_appointment.appointment_id = new.appointment_id_id
                and
                users_profile.id = staff_appointment.user_id_id
        )
        and clinic_id_id = (
            select clinic_id_id from staff_appointment
            where
                staff_appointment.appointment_id = new.appointment_id_id
        )
    ;

create or replace trigger bloodavailable_sub after insert on staff_bloodtopatient
for each row
    update staff_bloodavailable set units_available=units_available-1
    where
        blood_group=(
            select users_profile.blood_group from staff_appointment, users_profile
            where
                staff_appointment.appointment_id = new.appointment_id_id
                and
                users_profile.id = staff_appointment.user_id_id
        )
        and clinic_id_id = (
            select clinic_id_id from staff_appointment
            where
                staff_appointment.appointment_id = new.appointment_id_id
        )
    ;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20230416_2102'),
    ]

    operations = [
        migrations.RunSQL(SQL_QUERIES),
    ]
